// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyKhoaHoc.Models;

#nullable disable

namespace QuanLyKhoaHoc.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260413073432_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuanLyKhoaHoc.Models.DangKy", b =>
                {
                    b.Property<int>("MaDK")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDK"));

                    b.Property<int>("MaKH")
                        .HasColumnType("int");

                    b.Property<int>("MaSV")
                        .HasColumnType("int");

                    b.HasKey("MaDK");

                    b.HasIndex("MaKH");

                    b.HasIndex("MaSV");

                    b.ToTable("DangKys");
                });

            modelBuilder.Entity("QuanLyKhoaHoc.Models.KhoaHoc", b =>
                {
                    b.Property<int>("MaKH")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKH"));

                    b.Property<string>("TenKH")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaKH");

                    b.ToTable("KhoaHocs");
                });

            modelBuilder.Entity("QuanLyKhoaHoc.Models.SinhVien", b =>
                {
                    b.Property<int>("MaSV")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaSV"));

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaSV");

                    b.ToTable("SinhViens");
                });

            modelBuilder.Entity("QuanLyKhoaHoc.Models.DangKy", b =>
                {
                    b.HasOne("QuanLyKhoaHoc.Models.KhoaHoc", "KhoaHoc")
                        .WithMany("DangKys")
                        .HasForeignKey("MaKH")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyKhoaHoc.Models.SinhVien", "SinhVien")
                        .WithMany("DangKys")
                        .HasForeignKey("MaSV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhoaHoc");

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("QuanLyKhoaHoc.Models.KhoaHoc", b =>
                {
                    b.Navigation("DangKys");
                });

            modelBuilder.Entity("QuanLyKhoaHoc.Models.SinhVien", b =>
                {
                    b.Navigation("DangKys");
                });
#pragma warning restore 612, 618
        }
    }
}
